CREATE TABLE "drug" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "drug_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"slug" text NOT NULL,
	"drug_class_id" integer NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "drug_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
ALTER TABLE "drug" ADD CONSTRAINT "drug_drug_class_id_drug_class_id_fk" FOREIGN KEY ("drug_class_id") REFERENCES "public"."drug_class"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "drug_drugClassId_idx" ON "drug" USING btree ("drug_class_id");